web:
  build: ./
  ports:
    - "8080:80"
  volumes:
    - ./:/var/www
    - ./nginx/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php

php:
  image: nmcteam/php56
  expose:
    - 9000:9000
  volumes:
    - ./nginx/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./:/var/www
  links:
    - db

db:
  image: mysql
  environment:
   - MYSQL_DATABASE=bookyou
   - MYSQL_USER=root
   - MYSQL_PASSWORD=toor
